#include "Menu.h"

enum StaticMenuElems
{
	BACKGROUND, FRAME_FILE_INFO, FRAME_CURR_STAGE, FRAME_SELECT, FRAME_CONTINUE, FRAME_CONFIG, BORDER1, BORDER2, BORDER_3, COUNT1
};

enum DynamicMenuElems
{
	FLAME, COUNT2
};